#!/bin/bash
# Script for open CUPS webpage and install it if not installed
# If cups is running open the default browser in https://localhost:631
# If cups is not installed installl cups and open browser

# NO CUPS INSTALLED
if [ "$1" = "-I" ]; then
    # INSTALL CUPS
    if ! pacman -Qq cups &>/dev/null | grep -q "^ii"; then
        # Install package
        echo "CUPS is not installed"
        while true; do
            read -p "Install cups? (Y/n) " q
            [ "${q,,}" = "n" ] && exit
            ([ ! "$q" ] || [ "${q,,}" = "y" ]) && break
        done
        echo
        pacman -Sy --noconfirm cups || exit 1

        # Adduser to lpadmin
        echo
        echo "===================================================================="
        read -p "Select users to allow admin printers (space separated): " ul
        for u in $ul; do
            sudo adduser $u lpadmin
        done

        # Open browser
        echo
        read -p "Press enter to open CUPS admin page"
        xdg-open "http://localhost:631"
    # START CUPS
    else
        echo "CUPS is installed but not running"
        read -p "Press enter to try to start CUPS"
        sudo systemctl start cups.service
        sleep 1
        systemctl status cups &>/dev/null && xdg-open "http://localhost:631"
    fi

# OPEN CUPS ADMIN
elif systemctl status cups &>/dev/null; then
    xdg-open "http://localhost:631"
    exit

# CALL TO INSTALL CUPS
else
    terminator -e "$(readlink -f "$0")" -I
fi
